#!/usr/bin/env python3
"""
traefik_config.py — generate per-system Traefik dynamic config files.

Each file creates ONE router for ONE hostname. The router:
  1. Matches Host(<hostname>) on entrypoint 'web'
  2. Applies the shared 'wikijs-forwarded-headers' middleware (X-Forwarded-Proto: https)
  3. Applies a system-specific redirectregex middleware that turns
     '/' into the L2 redirect path '/<wiki-locale>/<system-slug>/anvandardokumentation/?lang=<default>'
  4. Routes to the wikijs backend (typically http://wikijs-app:3000)

A separate `wikijs-shared.yml` file holds middlewares used by every per-system
file. It's created on first use and left alone on subsequent runs.

Filename convention:
  <traefik-dynamic-dir>/wikijs-<system-slug>.yml
  <traefik-dynamic-dir>/wikijs-shared.yml          (created once)

Idempotency:
  Per-system file: written only when content differs.
  Shared file:     created only if missing.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


SHARED_TEMPLATE = """# Generated by system-docs-domain skill — do not edit by hand.
# Shared Traefik middleware used by all wikijs-<slug>.yml files.
#
# This file is created on first use of the system-docs-domain skill and
# left alone on subsequent runs. Delete it only if you also delete every
# wikijs-<slug>.yml that references it.

http:
  middlewares:
    wikijs-forwarded-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
"""


TEMPLATE = """# Generated by system-docs-domain skill — do not edit by hand.
# Created for system: {system_slug}
# Hostname:           {hostname}
# Redirect target:    {redirect_target}
#
# Re-run the skill to update; this file is rewritten on every successful run.

http:
  routers:
    wikijs-{system_slug}:
      rule: "Host(`{hostname}`)"
      entryPoints:
        - web
      service: wikijs-{system_slug}
      middlewares:
        - wikijs-forwarded-headers@file
        - wikijs-{system_slug}-redirect

  middlewares:
    wikijs-{system_slug}-redirect:
      redirectRegex:
        # Match the bare host (with optional trailing slash) only.
        # Anything deeper than '/' is left alone so internal wiki links work.
        regex: "^https?://{hostname_re}/?$"
        replacement: "https://{hostname}{redirect_target}"
        permanent: false

  services:
    wikijs-{system_slug}:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "{backend_url}"
"""


def _escape_regex(s: str) -> str:
    """Escape dots so the regex matches the literal hostname."""
    return s.replace(".", r"\.")


def shared_file_path(dynamic_dir: Path) -> Path:
    return dynamic_dir / "wikijs-shared.yml"


def ensure_shared_middleware(
    dynamic_dir: Path,
    *,
    dry_run: bool = False,
) -> tuple[Path, bool]:
    """Create wikijs-shared.yml if it doesn't exist.

    Returns (path, created). `created=False` means the file already existed
    and was left alone (we never overwrite — operator may have added other
    shared middlewares).
    """
    if not dynamic_dir.exists():
        raise FileNotFoundError(f"Traefik dynamic config dir not found: {dynamic_dir}")
    target = shared_file_path(dynamic_dir)
    if target.exists():
        return target, False
    if not dry_run:
        target.write_text(SHARED_TEMPLATE, encoding="utf-8")
    return target, True


def render_config(
    system_slug: str,
    hostname: str,
    redirect_target: str,
    backend_url: str,
) -> str:
    """Render the YAML for one system's domain alias.

    Args:
        system_slug: e.g. "docpilot"
        hostname:    e.g. "docs.docpilot.se"
        redirect_target: absolute path with leading slash, e.g.
                         "/sv/docpilot/anvandardokumentation/?lang=sv"
        backend_url: e.g. "http://wikijs-app:3000"
    """
    if not redirect_target.startswith("/"):
        raise ValueError("redirect_target must start with /")
    return TEMPLATE.format(
        system_slug=system_slug,
        hostname=hostname,
        hostname_re=_escape_regex(hostname),
        redirect_target=redirect_target,
        backend_url=backend_url,
    )


def file_path(dynamic_dir: Path, system_slug: str) -> Path:
    return dynamic_dir / f"wikijs-{system_slug}.yml"


def write_config(
    dynamic_dir: Path,
    system_slug: str,
    hostname: str,
    redirect_target: str,
    backend_url: str,
    *,
    dry_run: bool = False,
) -> tuple[Path, bool]:
    """Write the per-system config file. Also ensures wikijs-shared.yml exists.

    Returns (path, changed) where changed=False means the file already
    contained the desired content and was not rewritten.
    """
    if not dynamic_dir.exists():
        raise FileNotFoundError(f"Traefik dynamic config dir not found: {dynamic_dir}")

    # Ensure shared middleware file exists before writing per-system file
    ensure_shared_middleware(dynamic_dir, dry_run=dry_run)

    target = file_path(dynamic_dir, system_slug)
    new_content = render_config(system_slug, hostname, redirect_target, backend_url)

    existing = target.read_text(encoding="utf-8") if target.exists() else None
    if existing == new_content:
        return target, False

    if not dry_run:
        target.write_text(new_content, encoding="utf-8")
    return target, True


def remove_config(dynamic_dir: Path, system_slug: str) -> bool:
    """Delete the per-system config file. Returns True if the file existed.

    Does NOT remove wikijs-shared.yml since other systems may still use it.
    """
    target = file_path(dynamic_dir, system_slug)
    if not target.exists():
        return False
    target.unlink()
    return True


def build_redirect_target(
    wiki_locale: str,
    system_slug: str,
    default_locale: str,
    extra_path: str = "anvandardokumentation",
) -> str:
    """Construct the absolute path users land on after Traefik redirects.

    Returns: /<wiki-locale>/<system-slug>/<extra-path>/?lang=<default-locale>
    """
    parts = [wiki_locale.strip("/"), system_slug.strip("/"), extra_path.strip("/")]
    path = "/" + "/".join(p for p in parts if p) + "/"
    return f"{path}?lang={default_locale}"


# ----- CLI ----------------------------------------------------------------


def main() -> int:
    p = argparse.ArgumentParser(prog="traefik_config")
    sub = p.add_subparsers(dest="cmd", required=True)

    w = sub.add_parser("write", help="Write the per-system Traefik config file")
    w.add_argument("--system-slug", required=True)
    w.add_argument("--hostname", required=True)
    w.add_argument("--wiki-locale", default=None,
                   help="Wiki.js display locale; defaults to WIKIJS_DEFAULT_LOCALE")
    w.add_argument("--default-locale", default=None,
                   help="Documentation default locale for ?lang=; "
                        "defaults to WIKIJS_DEFAULT_LOCALE")
    w.add_argument("--dynamic-dir", default=None,
                   help="Traefik dynamic config directory; defaults to "
                        "TRAEFIK_DYNAMIC_CONFIG_DIR")
    w.add_argument("--backend-url", default=None,
                   help="Wiki.js backend URL; defaults to WIKIJS_BACKEND_URL")
    w.add_argument("--dry-run", action="store_true")

    rm = sub.add_parser("remove", help="Delete the per-system Traefik config file")
    rm.add_argument("--system-slug", required=True)
    rm.add_argument("--dynamic-dir", default=None)

    sh = sub.add_parser("ensure-shared", help="Create wikijs-shared.yml if missing")
    sh.add_argument("--dynamic-dir", default=None)
    sh.add_argument("--dry-run", action="store_true")

    args = p.parse_args()

    dynamic_dir = Path(
        args.dynamic_dir or os.environ.get("TRAEFIK_DYNAMIC_CONFIG_DIR", "")
    )
    if not dynamic_dir or str(dynamic_dir) == ".":
        print("Provide --dynamic-dir or set TRAEFIK_DYNAMIC_CONFIG_DIR",
              file=sys.stderr)
        return 2

    if args.cmd == "write":
        wiki_locale = args.wiki_locale or os.environ.get("WIKIJS_DEFAULT_LOCALE", "sv")
        default_locale = args.default_locale or wiki_locale
        backend = args.backend_url or os.environ.get(
            "WIKIJS_BACKEND_URL", "http://wikijs-app:3000"
        )
        target = build_redirect_target(wiki_locale, args.system_slug, default_locale)
        path, changed = write_config(
            dynamic_dir, args.system_slug, args.hostname,
            target, backend, dry_run=args.dry_run,
        )
        action = "would write" if args.dry_run else ("wrote" if changed else "unchanged")
        print(f"{action}: {path}")
        return 0

    if args.cmd == "remove":
        removed = remove_config(dynamic_dir, args.system_slug)
        print(f"{'removed' if removed else 'no file to remove'}: "
              f"{file_path(dynamic_dir, args.system_slug)}")
        return 0

    if args.cmd == "ensure-shared":
        path, created = ensure_shared_middleware(dynamic_dir, dry_run=args.dry_run)
        action = ("would create" if args.dry_run and created
                  else "created" if created else "exists")
        print(f"{action}: {path}")
        return 0

    return 2


if __name__ == "__main__":
    sys.exit(main())
